version: 2
jobs:
  deploy:
    machine:
        image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: Deploy slides
          command: |
            ssh $SSH_USER@$SSH_HOST git --git-dir=slides/.git --work-tree=slides fetch --prune origin
            ssh $SSH_USER@$SSH_HOST git --git-dir=slides/.git --work-tree=slides reset --hard origin/master
            ssh $SSH_USER@$SSH_HOST git --git-dir=slides/.git --work-tree=slides clean -fd
            ssh $SSH_USER@$SSH_HOST slides/.circleci/update-local-asset.sh

workflows:
  version: 2
  deploy-slides:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
