version: 2
jobs:
  deploy:
    machine:
        image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: SSH 経由のデプロイ
          command: |
            ssh $SSH_USER@$SSH_HOST rm -rf slides/*
            scp -r ./* $SSH_USER@$SSH_HOST:slides/
      
workflows:
  version: 2
  deploy-slides:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
